/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AggregatesImport } from './routes/aggregates'
import { Route as ConfigImport } from './routes/config'
import { Route as ResultsImport } from './routes/results'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AggregatesRoute = AggregatesImport.update({
  id: '/aggregates',
  path: '/aggregates',
  getParentRoute: () => rootRoute,
} as any)

const ConfigRoute = ConfigImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRoute,
} as any)

const ResultsRoute = ResultsImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/aggregates': {
      id: '/aggregates'
      path: '/aggregates'
      fullPath: '/aggregates'
      preLoaderRoute: typeof AggregatesImport
      parentRoute: typeof rootRoute
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigImport
      parentRoute: typeof rootRoute
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aggregates': typeof AggregatesRoute
  '/config': typeof ConfigRoute
  '/results': typeof ResultsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aggregates': typeof AggregatesRoute
  '/config': typeof ConfigRoute
  '/results': typeof ResultsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/aggregates': typeof AggregatesRoute
  '/config': typeof ConfigRoute
  '/results': typeof ResultsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aggregates' | '/config' | '/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aggregates' | '/config' | '/results'
  id: '__root__' | '/' | '/aggregates' | '/config' | '/results'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AggregatesRoute: typeof AggregatesRoute
  ConfigRoute: typeof ConfigRoute
  ResultsRoute: typeof ResultsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AggregatesRoute: AggregatesRoute,
  ConfigRoute: ConfigRoute,
  ResultsRoute: ResultsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
